### ISSUE TITLE
bad file or name

### ISSUE THREAD

**Issue by NbR404** [0v3rl0w/e013#1]
![capture](https://user-images.githubusercontent.com/4534656/37330681-86c20cb8-26aa-11e8-9004-54ef825e264c.PNG)

**Comment by 0v3rl0w** [comment]
Hello, thank you for your report, can you give me the name of the wifi you want to find the password ?

**Comment by NbR404** [comment]
BlackHat>V1p3r     -is the name of the wifi (my home network)

**Comment by 0v3rl0w** [comment]
Ok I will fix it

**Comment by NbR404** [comment]
Ya! it works!
