### ISSUE TITLE
Is it possible to make send the file to an email/ftp ?!

### ISSUE THREAD

**Issue by minanagehsalalma** [0v3rl0w/e013#1]

**Comment by keyboard-slayer** [comment]
Hi, sorry for responding that late, but yeah it's possible, maybe i'll put it one day 

Thanks for using my script 👍

**Comment by keyboard-slayer** [comment]
I committed a new file named  `ε013-ftp.vbs`. 
Hope that you'll enjoy it 😄 

Don't hesitate to give me feedbacks !

**Comment by minanagehsalalma** [comment]
@0v3rl0w  great mate but how does it work ?
so it needs a firewall allow filter  when host isn't ?

> HOST = "localhost"

**Comment by keyboard-slayer** [comment]
You just have to replace the variables with your FTP server's informations and no need to disable any firewall because I use the FTP client built-in Windows

**Comment by minanagehsalalma** [comment]
> You just have to replace the variables with your FTP server's informations and no need to disable any firewall because I use the FTP client built-in Windows

@0v3rl0w  ... i think it's a little bit not safe to store FTP server's informations on clear text .vbs

**Comment by keyboard-slayer** [comment]
I can tell you that it's impossible to properly hide the password. Even in another programming language. If I redo it in C++ for example, you'll be able to see it in plain text in the binary. 

If you have an idea how I can hide it don't hesitate to share your idea :)

**Comment by minanagehsalalma** [comment]
> I can tell you that it's impossible to properly hide the password. Even in another programming language. If I redo it in C++ for example, you'll be able to see it in plain text in the binary.
> 
> If you have an idea how I can hide it don't hesitate to share your idea :)

@0v3rl0w 
i don't really know .. but i have read about a way that Depends on receiving the password only when the attack tries to run ... receive it from  a server maybe .. in more controllable way like you got the request then you allow the server to send the password but on parts ..

and i think there is a better way to send the wifi password maybe using query stings 
what do you think ?

**Comment by keyboard-slayer** [comment]
So, I've just made a kind of One Time HTTP Server (so when it reads a file it deletes it directly) (see [HERE](https://gist.github.com/0v3rl0w/037cffc25649061b6492c8b43e7f3b25)), but because I don't have access to a Window computer at the moment. So I'm not able to make a HTTP Patch for the script at the moment

**Comment by minanagehsalalma** [comment]
> So, I've just made a kind of One Time HTTP Server (so when it reads a file it deletes it directly) (see [HERE](https://gist.github.com/0v3rl0w/037cffc25649061b6492c8b43e7f3b25)), but because I don't have access to a Window computer at the moment. So I'm not able to make a HTTP Patch for the script at the moment
@0v3rl0w  
you mean once it read the password it deletes the file that contains the password ? 

what about the query string trick to send the password to web server using a url just like this 
www.test.com/pass?ssid=dsadsad&pass=46d4sa65d4

**Comment by minanagehsalalma** [comment]
and it's written in ruby , right ?
i can't test it !

> (see [HERE](https://gist.github.com/0v3rl0w/037cffc25649061b6492c8b43e7f3b25)),

**Comment by keyboard-slayer** [comment]
Yeah it's written in ruby, because sockets are easier in ruby

**Comment by minanagehsalalma** [comment]
@0v3rl0w  well i don't know how to run ruby on windows !!

**Comment by keyboard-slayer** [comment]
Well, [Here's the solution](http://bfy.tw/OEN3)

**Comment by minanagehsalalma** [comment]
@0v3rl0w  lol that was funny ...
btw you didn't explain what does that script do or even what  do i need to change to make it work?

**Comment by keyboard-slayer** [comment]
I explained everything about the script earlier, it's an HTTP Server that, when you ask a file (http://localhost/password.txt for example), it destroy it immediately.

But you'll need to modify some stuff in e013-ftp.vbs to make it work proberly. Feel free to fork it and do your own modifications.

**Comment by minanagehsalalma** [comment]
> I explained everything about the script earlier, it's an HTTP Server that, when you ask a file (http://localhost/password.txt for example), it destroy it immediately.
> 
> But you'll need to modify some stuff in e013-ftp.vbs to make it work proberly. Feel free to fork it and do your own modifications.


@0v3rl0w 
you mean it destroies it after using it like it's a one time password ?

**Comment by keyboard-slayer** [comment]
Yes it is

**Comment by minanagehsalalma** [comment]
@0v3rl0w  it seems Great but i don't think i have the enough skill to 
"But you'll need to modify some stuff in e013-ftp.vbs to make it work proberly. Feel free to fork it and do your own modifications."

and what about the
"the query string trick to send the password to web server using a url just like this
www.test.com/pass?ssid=dsadsad&pass=46d4sa65d4"

**Comment by keyboard-slayer** [comment]
Yes, it can be easily archived with a little bit of PHP, I'll add it into the project page of the repo ;)

**Comment by minanagehsalalma** [comment]
@0v3rl0w  thanks mate i have the PHP part of code if you want it anyway :)

**Comment by keyboard-slayer** [comment]
You're welcome, but I prefer to do it by myself, thank you anyway :+1:

**Comment by keyboard-slayer** [comment]
I pushed the code with all the features you asked, if you have any issue, feel free to open another issue.

**Comment by minanagehsalalma** [comment]
@0v3rl0w awesome but how do i run it and what do i need to change else than HOST = "http://localhost:8000/e013-http.php"

And i got this while trying to run it !!
![image](https://user-images.githubusercontent.com/20546638/60130081-cf47f980-9796-11e9-91e0-e70752852959.png)

and i need to upload the php file first on my server right ?

and got this when i tried the ftp one 
![image](https://user-images.githubusercontent.com/20546638/60130911-75e0ca00-9798-11e9-8b3c-ce7225bbf03e.png)

.... 
and do you think that this will work with it ?
![image](https://user-images.githubusercontent.com/20546638/60130962-91e46b80-9798-11e9-8c46-3449d5f3880e.png)
..
and why do you think it failed to connect using cmd ?
![image](https://user-images.githubusercontent.com/20546638/60131051-bfc9b000-9798-11e9-8fb9-e2575e60b4e3.png)


thanks :)

**Comment by minanagehsalalma** [comment]
i tried the ftp ip instead of the domain name and it connected in the cmd but still the vbs didn't work !!!

**Comment by keyboard-slayer** [comment]
For the first error, I have an idea for that (I'll do a fix very very soon), and can you do a screenshot of the code of the ftp version. Because I don't have any errors while running it

**Comment by keyboard-slayer** [comment]
So you put in HOST : 

http://YOUR_WEBSITE_ADDR_HERE/THE_NAME_OF_THE_PHP_SCRIPT.php

**Comment by minanagehsalalma** [comment]
> For the first error, I have an idea for that (I'll do a fix very very soon), and can you do a screenshot of the code of the ftp version. Because I don't have any errors while running it

![image](https://user-images.githubusercontent.com/20546638/60187770-7035c380-982e-11e9-8176-85ff06579f4b.png)

This is the error 

and the code 
![image](https://user-images.githubusercontent.com/20546638/60188013-e63a2a80-982e-11e9-94dd-2e9dce3dd316.png)

**Comment by keyboard-slayer** [comment]
Do you have any line before the HOST line ?

**Comment by minanagehsalalma** [comment]
No

**Comment by minanagehsalalma** [comment]
@0v3rl0w  i got it working now ... the problem was saving it using notepad it messed up the unicode or some thing
check this for more info https://www.computerperformance.co.uk/error-codes/800a0408/ 
or 
https://stackoverflow.com/questions/2039104/vbscript-invalid-character-800a0408-compilation-error
and you should mention this in README.md
 .... 
but i am unable to connect to my server i don't why !
but when i tired it on a local server i faced another problem that your script doesn't support custom ports !!
you should check this for a fix 
https://superuser.com/questions/1248499/cannot-connect-to-non-standard-port-number-with-windows-command-line-ftp-cmd-ft

**Comment by minanagehsalalma** [comment]
@0v3rl0w  and another bug 
in one of the exported password files it picked out the string Present instead of the password that starts with #
![image](https://user-images.githubusercontent.com/20546638/60223344-bf0c4900-9880-11e9-9430-b03cf3ba57fd.png)

![image](https://user-images.githubusercontent.com/20546638/60223508-cb90a180-9880-11e9-97b3-771cd33e039c.png)

**Comment by keyboard-slayer** [comment]
Voila, I fixed the problem can you try it please ?

**Comment by minanagehsalalma** [comment]
@0v3rl0w whoooa it works like a charm but here one last problem 
![image](https://user-images.githubusercontent.com/20546638/60290135-583a6e80-9918-11e9-8c35-5fc0281584cb.png)
in this one using the http method the network name wasn't complete and  the password is wrong it's not a part of the network name 
the network name "test-PC_Network"
the script named the file test- and putted network as it's password !!
and btw why does it use powershell ?!
and can we make it a little bit noise less like open the network tabs in the background ? 
and can we base64 encode the password and maybe the wifi ssid maybe ? and opening it in incognito window ? 

i have tested the ftp one too and it works just Great :)
Keep it up mate

**Comment by minanagehsalalma** [comment]
@0v3rl0w  and an Option to cd a Specific folder  before uploading the files in FTP would really be useful !

**Comment by minanagehsalalma** [comment]
> and btw why does it use powershell ?!


as this will make it doesn't work on older windows versions like 7

**Comment by keyboard-slayer** [comment]
The http version use powershell to encode the password and the wifi name in URL format, because it was easier. For the HTTP issue and the FTP I'll do an update

**Comment by keyboard-slayer** [comment]
And because Windows version greater than 7 represent all most 90% of the all market share [Source](https://www.statista.com/statistics/993868/worldwide-windows-operating-system-market-share/), I won't remove Powershell, because it's easier for the HTTP Version

**Comment by minanagehsalalma** [comment]
> And because Windows version greater than 7 represent all most 90% of the all market share [Source](https://www.statista.com/statistics/993868/worldwide-windows-operating-system-market-share/), I won't remove Powershell, because it's easier for the HTTP Version

maybe curl would be easier and better and would work for win 7 i think ...
"The http version use powershell to encode the password and the wifi name in URL format"
[why just not base64 encode it ?
](https://stackoverflow.com/questions/37046771/base64-encode-string-command-line-windows)
Then the php script decode it and parse it.
@0v3rl0w

**Comment by keyboard-slayer** [comment]
The problem is that I want no dependencies on this code, for making as portable as possible. So it  wouldn't be possible to implement Curl or Base64. 
(Except if I write my own base64 encoder)

For CURL, it wouldn't be possible because i'll need dependencies (the one needed is the one you had issue with here). I can download it with Powershell, but it would be pointless. 

> @0v3rl0w awesome but how do i run it and what do i need to change else than HOST = "http://localhost:8000/e013-http.php"
> 
> And i got this while trying to run it !!
> ![image](https://user-images.githubusercontent.com/20546638/60130081-cf47f980-9796-11e9-91e0-e70752852959.png)
> 
> and i need to upload the php file first on my server right ?
> 
> and got this when i tried the ftp one
> ![image](https://user-images.githubusercontent.com/20546638/60130911-75e0ca00-9798-11e9-8b3c-ce7225bbf03e.png)
> 
> ....
> and do you think that this will work with it ?
> ![image](https://user-images.githubusercontent.com/20546638/60130962-91e46b80-9798-11e9-8c46-3449d5f3880e.png)
> ..
> and why do you think it failed to connect using cmd ?
> ![image](https://user-images.githubusercontent.com/20546638/60131051-bfc9b000-9798-11e9-8fb9-e2575e60b4e3.png)
> 
> thanks :)

**Comment by minanagehsalalma** [comment]
> For CURL, it wouldn't be possible because i'll need dependencies


[why isn't it already implanted in windows ? 
](https://stackoverflow.com/a/16216825/11694684)"(Except if I write my own base64 encoder)"
[i don't think that's there is need for that powershell have this function already 
](https://adsecurity.org/?p=478)
@0v3rl0w

**Comment by keyboard-slayer** [comment]
Of course, but I don't see why the script needs base64 encoding

**Comment by minanagehsalalma** [comment]
@0v3rl0w 
cause sending passwords via http requests isn't safe at all i think .

**Comment by keyboard-slayer** [comment]
Base64 isn't safe too, it's very very very easy to decode it.
But if you want it to be safe, just take a hosting with https, it'll be safer

**Comment by minanagehsalalma** [comment]
@0v3rl0w  "Base64 isn't safe too" 
i know but it's better than plain text and will not catch that Attention ... 
"just take a hosting with https" 
i don't think that it will be safer .. cause even with https you still be able to catch the url which the password is in ... but not be able to decrypt the content of that https traffic.

**Comment by keyboard-slayer** [comment]
I won't implement base64, because the script will be slower. Normally it won't catch any attentions because the browser tab close it self automatically;
